Домашка по уроку 12.Методы объектов.
SergeiAnishchenko/Lesson12.ObjectsMethods pull request #1
Opened 2023-01-12 17:59 UTC by SergeiAnishchenko

Привет!
Прошу проверить домашку по уроку 12. Методы объектов.

2023-01-12 18:46 UTC, OlgaLugacheva requested changes

2023-01-12 18:46 UTC, OlgaLugacheva commented on src/Author.java
> +        if (this.getClass() != other.getClass()) {
если мы и собственноручно переопределяем equals то не забываем проверку на null
также не забываем проверку на идентичность this == other

2023-01-12 18:46 UTC, OlgaLugacheva commented on src/Book.java
> +        if (this.getClass() != other.getClass()) {
см комментарий выше

2023-01-12 20:07 UTC, SergeiAnishchenko commented on src/Author.java
> +        if (this.getClass() != other.getClass()) {
Спасибо! Внес корректировку в метод.

2023-01-12 20:07 UTC, SergeiAnishchenko commented on src/Book.java
> +        if (this.getClass() != other.getClass()) {
Спасибо! Внес корректировку в метод.

2023-01-13 07:10 UTC, OlgaLugacheva approved these changes

2023-01-15 12:14 UTC, merged